version: '3'

services:
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "c:/Users/admin/config/:/etc/selenoid/:ro"
      - "c:/Users/admin/selenoid/video/:/opt/selenoid/video/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/admin/selenoid/video/
    command: ["start"]

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
